"""Persistent, user-scoped chat history stored in SQLite or PostgreSQL."""

from __future__ import annotations

import os
from pathlib import Path

from core.database import adapt_query, connect, uses_postgres

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
DB_PATH = Path(os.getenv("PUBMED_DB_PATH", Path(__file__).resolve().parents[1] / "pubmed.db"))

_SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    conversation_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)
"""

_POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    conversation_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)
"""


def _connect():
    return connect(DATABASE_URL, DB_PATH)


def _query(query: str) -> str:
    return adapt_query(query, DATABASE_URL)


def init_chat_db() -> None:
    with _connect() as connection:
        connection.execute(
            _POSTGRES_SCHEMA if uses_postgres(DATABASE_URL) else _SQLITE_SCHEMA
        )
        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation
            ON chat_messages(user_id, conversation_id, id)
            """
        )


def append_message(user_id: str, conversation_id: str, role: str, content: str) -> None:
    user_id = _normalize_required(user_id, "user_id").casefold()
    conversation_id = _normalize_required(conversation_id, "conversation_id")
    content = _normalize_required(content, "content")
    if role not in {"user", "assistant"}:
        raise ValueError("role must be 'user' or 'assistant'")

    init_chat_db()
    with _connect() as connection:
        connection.execute(
            _query(
                """
            INSERT INTO chat_messages (user_id, conversation_id, role, content)
            VALUES (?, ?, ?, ?)
            """,
            ),
            (user_id, conversation_id, role, content),
        )


def get_messages(
    user_id: str,
    conversation_id: str,
    limit: int = 200,
) -> list[dict]:
    user_id = _normalize_required(user_id, "user_id").casefold()
    conversation_id = _normalize_required(conversation_id, "conversation_id")
    if isinstance(limit, bool) or not isinstance(limit, int) or limit < 1:
        raise ValueError("limit must be a positive integer")

    init_chat_db()
    with _connect() as connection:
        rows = connection.execute(
            _query(
                """
            SELECT role, content, created_at
            FROM (
                SELECT id, role, content, created_at
                FROM chat_messages
                WHERE user_id = ? AND conversation_id = ?
                ORDER BY id DESC
                LIMIT ?
            )
            ORDER BY id ASC
            """,
            ),
            (user_id, conversation_id, limit),
        ).fetchall()
    return [dict(row) for row in rows]


def _normalize_required(value: str, field: str) -> str:
    normalized = str(value or "").strip()
    if not normalized:
        raise ValueError(f"{field} must not be empty")
    return normalized
